# Generated by Django 5.2.3 on 2025-06-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('power', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hp', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=30)),

            ],
        ),
        migrations.CreateModel(
            name='CardAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.attack')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
            ],
        ),
    ]
