# Generated by Django 5.2.3 on 2025-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_card_image_booster_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booster',
            name='card',
        ),
        migrations.AddField(
            model_name='booster',
            name='name',
            field=models.CharField(default='Booster', max_length=30),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.CharField(default='base_set', max_length=30),
        ),
    ]
