# Generated by Django 5.2.3 on 2025-07-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_booster_card_booster_name_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='attack1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='attack1', to='backend.attack'),
        ),
        migrations.AddField(
            model_name='collection',
            name='attack2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack2', to='backend.attack'),
        ),
    ]
