# Generated by Django 5.2.3 on 2025-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_collection_attack1_collection_attack2'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='common', max_length=30),
        ),
    ]
