# Generated by Django 5.2.3 on 2025-09-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.collection')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.battle')),
                ('cards', models.ManyToManyField(to='backend.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player'),
        ),
        migrations.CreateModel(
            name='PlayerTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.battle')),
                ('bench_cards', models.ManyToManyField(related_name='player_benched_cards', to='backend.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
                ('player_active_cards', models.ManyToManyField(related_name='player_active_cards', to='backend.card')),
            ],
        ),
        migrations.CreateModel(
            name='BattleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cards', models.IntegerField()),
                ('active_cards', models.ManyToManyField(related_name='active_cards', to='backend.card')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.battle')),
                ('bench_cards', models.ManyToManyField(related_name='benched_cards', to='backend.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.playerturn')),
            ],
        ),
    ]
